Build/initial sql
G1-APSOO/CadastrarCliente pull request #3
Opened 2023-09-29 22:28 UTC by PedroOSilv

Conexao e ClienteDAO estão prontas, agora precisamos testar com o resto do programa.

2023-09-29 22:44 UTC, Mat780 requested changes
No ExGrupo.sql mudar o telefone de INT para VARCHAR, com no minimo 11 caracteres

2023-09-29 22:47 UTC, Mat780 requested changes
Atualizar o .gitignore para não importar a pasta bin, ela não precisa vir para a branch remota

2023-09-29 22:59 UTC, Mat780 requested changes
No ClienteDAO o atualizar cliente recebe como parametro apenas um cliente, quando na teoria ele receberia dois, sendo 1 a cópia do antigo e o outro o novo, ou se preferir ele recebe como parametro uma String CPF e um cliente, ai com o CPF você caça no BD e com a classe cliente você atualiza todas as infos daquele CPF dado, inclusive o CPF

2023-09-29 23:00 UTC, Mat780 requested changes
Todas as exceções que estão como "excessao" tem que ser excluidas.

2023-09-29 23:02 UTC, Mat780 commented
Fora as mudanças solicitadas o resto tá tudo certo! ^u^

2023-09-30 00:00 UTC, Mat780 commented
Então o gitignore acho que só precisa ignorar o /bin mesmo, o resto é importante ter para o código

2023-09-30 00:15 UTC, Mat780 approved these changes
LGTM

2023-09-30 00:16 UTC, GiovannaRMendes approved these changes

2023-09-30 00:17 UTC, merged